Doc415 addfavicon
TheCSharpAcademy/TCSA.V2 pull request #161
Opened 2024-03-15 08:48 UTC by Doc415

Added C# Academy favicon

2024-03-18 08:01 UTC, Doc415 commented
Updated "Submit PR form" in community projects page.
Since i cant test it locally, this is a blind shot.

2024-03-21 06:19 UTC, TheCSharpAcademy requested changes

2024-03-21 06:19 UTC, TheCSharpAcademy commented on TCSA.V2/Components/App.razor
> +    <link rel="icon" type="image/x-icon" href="/favicon.ico">
Hello! At the moment I see this icon. I was expecting the C# Academy icon?

2024-03-21 06:19 UTC, TheCSharpAcademy commented on TCSA.V2/Components/Dashboard/Pages/Community.razor
> +        await JsRuntime.InvokeVoidAsync("scrollToTop");
No JS please. 😁

2024-03-21 08:23 UTC, Doc415 commented on TCSA.V2/Components/App.razor
> +    <link rel="icon" type="image/x-icon" href="/favicon.ico">
I took it from the old site. Thats what i see in old site as favicon.

2024-03-21 08:27 UTC, Doc415 commented on TCSA.V2/Components/App.razor
> +    <link rel="icon" type="image/x-icon" href="/favicon.ico">
![image](https://github.com/TheCSharpAcademy/TCSA.V2/assets/94632226/12ba8942-24d5-4e9b-b26c-ae0b4ec84faa)
 this is from old site.

So I dont have any other file to put. If you can send me the icon file i ll replace it.

2024-03-21 08:29 UTC, Doc415 commented on TCSA.V2/Components/Dashboard/Pages/Community.razor
> +        await JsRuntime.InvokeVoidAsync("scrollToTop");
sure :)

2024-03-25 02:39 UTC, TheCSharpAcademy requested changes
@Doc415 This PR still contains too many changes. Could you please modify it so it only contains the changes relevant to the favicon?

2024-04-09 19:25 UTC, TheCSharpAcademy commented
@Doc415 Any updates?

2024-04-09 19:37 UTC, Doc415 commented
> @Doc415 Any updates? 😊

İ have created seperated pr  for each issue waitin for review :)

Pr no #189 and #190

2024-04-09 19:40 UTC, Doc415 commented
> @Doc415 Any updates? 😊

I have created seperated pr for each issue waiting for review :)

Pr #189 and #190

2024-04-12 22:23 UTC, closed without merging