245 fix ranking in email
TheCSharpAcademy/TCSA.V2 pull request #250
Opened 2024-05-04 20:38 UTC by kronyer

I think i did everything :)

2024-05-04 21:14 UTC, stevietv requested changes
just a minor typo in the var name

2024-05-04 21:14 UTC, stevietv commented on TCSA.V2/Components/Admin/Pages/UserDetail.razor
> +        var rankingWithSufix = LeaderboardHelper.GetRanking(rankingText);
```suggestion
        var rankingWithSuffix = LeaderboardHelper.GetRanking(rankingText);
```

2024-05-04 21:14 UTC, stevietv commented on TCSA.V2/Components/Admin/Pages/UserDetail.razor
> +        var body = EmailHelper.GetProjectCompletedBody(firstName, projectTitle, project.ExperiencePoints, rankingWithSufix.ToString());
```suggestion
        var body = EmailHelper.GetProjectCompletedBody(firstName, projectTitle, project.ExperiencePoints, rankingWithSuffix.ToString());
```

2024-05-04 21:14 UTC, stevietv commented on TCSA.V2/Components/Admin/Pages/UserDetail.razor
> +        var rankingWithSufix = LeaderboardHelper.GetRanking(rankingText);
```suggestion
        var rankingWithSuffix = LeaderboardHelper.GetRanking(rankingText);
```

2024-05-04 21:14 UTC, stevietv commented on TCSA.V2/Components/Admin/Pages/UserDetail.razor
> +        var body = EmailHelper.GetProjectCompletedBody(firstName, project.Title, project.ExperiencePoints, rankingWithSufix.ToString());
```suggestion
        var body = EmailHelper.GetProjectCompletedBody(firstName, project.Title, project.ExperiencePoints, rankingWithSuffix.ToString());
```

2024-05-04 22:27 UTC, kronyer commented
Sorry 😂 not so used to write in english

2024-05-05 08:00 UTC, stevietv commented
> Sorry 😂 not so used to write in english

no need to apologize!!!

2024-05-07 22:27 UTC, merged