Users can change pull request url
TheCSharpAcademy/TCSA.V2 pull request #392
Opened 2024-08-18 09:30 UTC by ukpagrace

Modified Code to Allow users to change their pull request
![Screenshot (50)](https://github.com/user-attachments/assets/d4d565af-5ae9-4021-984c-fe4d46de9e41)
![Screenshot (51)](https://github.com/user-attachments/assets/2f2ed7ef-2d5a-452c-9d7e-867146a46c13)
![Screenshot (49)](https://github.com/user-attachments/assets/d780cd30-d936-4181-93fc-cae4768161e5)

2024-08-18 12:52 UTC, dmarcoux commented on TCSA.V2/Components/Dashboard/Pages/ProjectSubmission.razor
> +        <div class="mt-5 pt-5">
With the introduction of these changes, I would suggest removing some of the duplication in the HTML markup in this page. A sizable part of the HTML is always the same in every `if/else` branch:

```html
        <div class="mt-5 pt-5">
            <div class="card submit-project-card bg-@(backgroundClass)">
                <div class="card-body">
                    @cardContent
                </div>
            </div>
        </div>
``` 

Above is only an example of what could be abstracted. The background class and maybe even the card content, which ends up being a short message in most `if/else` branches.

2024-08-18 12:55 UTC, dmarcoux commented on TCSA.V2/Components/Dashboard/Pages/ProjectSubmission.razor
> +                    This Project has been Marked Completed
To use a consistent case:

```suggestion
                    This project has been marked as completed.
```

2024-08-18 13:30 UTC, ukpagrace commented on TCSA.V2/Components/Dashboard/Pages/ProjectSubmission.razor
> +        <div class="mt-5 pt-5">
I'm thinking, Abstracting card content would be putting it in a component file. Isn't it too small for it?

2024-08-18 13:54 UTC, dmarcoux commented on TCSA.V2/Components/Dashboard/Pages/ProjectSubmission.razor
> +        <div class="mt-5 pt-5">
We could always wait to see how it goes. If we end up having another instance of this HTML in the future, then I would suggest going with a component. Even if it's quite small.

2024-08-18 15:58 UTC, ukpagrace commented on TCSA.V2/Components/Dashboard/Pages/ProjectSubmission.razor
> +                    This Project has been Marked Completed
noted, thanks.

2024-08-18 15:58 UTC, ukpagrace commented on TCSA.V2/Components/Dashboard/Pages/ProjectSubmission.razor
> +        <div class="mt-5 pt-5">
okay

2024-08-26 06:02 UTC, TheCSharpAcademy commented on TCSA.V2/Components/Dashboard/Pages/ProjectSubmission.razor
> +        <div class="mt-5 pt-5">
@dmarcoux Thanks for your input! It's always good to have another pair of experienced eyes in these reviews! 👌🏻👌🏻😁

2024-08-26 06:18 UTC, TheCSharpAcademy requested changes
@ukpagrace thanks for submitting! At the moment I can update the PR but I'll request two changes for better UX.

1 - In the dashboard main page: change the button label to view/edit instead of just view, otherwise it's not intuitive that the PR can be updated from there. Also, it would be good if the icon itself was clickable too. And I'm the card for the project underreview should have a yellow border. 

2 - This is optional, if you think it's too much work I can create a separate ticket. But you could create a button similar to Show Completed, but Show Pending.

If that button is clicked you need change the button show it reverses the action. Also, you'd need to show a list of Project Cards, as opposed to Area Cards. Let me know if you want to work on this of if I should create a separate ticket. 😄

Is that ok? Thank you!

2024-08-26 06:22 UTC, ukpagrace commented
@TheCSharpAcademy Thanks for the detailed review.
Noted on the required changes and yes I would on it.

2024-08-28 19:05 UTC, stevietv commented
> @ukpagrace thanks for submitting! At the moment I can update the PR but I'll request two changes for better UX.
> 
> 1 - In the dashboard main page: change the button label to view/edit instead of just view, otherwise it's not intuitive that the PR can be updated from there. Also, it would be good if the icon itself was clickable too. And I'm the card for the project underreview should have a yellow border.

@TheCSharpAcademy 
I think it should be the pending button that becomes `Pending/Edit` not the view button?
the NavLink should indeed include the SVG for the icon inside it.

2024-09-02 14:22 UTC, merged