notifying users of the status of their project according
TheCSharpAcademy/TCSA.V2 pull request #397
Opened 2024-08-23 21:44 UTC by ukpagrace

Users are notified the status of their project, whether under review or completed.

2024-08-26 06:25 UTC, TheCSharpAcademy requested changes
@ukpagrace Going to review this once the "PR Update" ticket is done. Please make sure you update this branch once that ticket is merged.

2024-08-29 17:34 UTC, stevietv commented on TCSA.V2/Components/UI/SVGs/PendingReviewSVG.razor
NavLink should be around the svg also instead of just the text so that the icon is also clickable

2024-09-02 15:58 UTC, TheCSharpAcademy requested changes
@ukpagrace Conflicts 🥲

2024-09-02 17:34 UTC, ukpagrace commented
Noted, Would rectify it

2024-09-07 03:58 UTC, ukpagrace commented
Hey @TheCSharpAcademy , so sorry
I was waiting for you to merge the fix so that I could pull it at once.
I forgot about the conflicts.

2024-09-11 11:21 UTC, merged